#!/usr/bin/env ruby
#
# This file is gererated by ruby-glade-create-template 1.1.4.
#
GNB_PLATFORM = 'gnome'

require 'rubygems'
require File.dirname(__FILE__)+"/lib/app/#{GNB_PLATFORM}/server_list_controller"

GNB::ServerListController.new.run
